services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: act-officiel-web
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.act-officiel.rule=Host(`a-ct.ma`) || Host(`www.a-ct.ma`) || Host(`africacentredtechnology.com`) || Host(`www.africacentredtechnology.com`)"
      - "traefik.http.routers.act-officiel.entrypoints=web"
      - "traefik.http.services.act-officiel.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
